title:              Phenikaa AI Lab - Blog
home:               Phenikaa AI
excerpt:            PAIL AI Tech Blogs
email:              trang.maixuan@phenikaa-uni.edu.vn
description:        Blog about Artificial Intelligence by PAIL
author:             PAIL
baseurl:            "/blog"
url:                "https://pail.phenikaa-uni.edu.vn/"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
rouge: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
